services:
  server:
    build: ./server
    ports:
      - 8080:8080
    environment:
      - ADDR=:8080
      - DIFFICULTY=4
    networks:
      - wow-net

  client:
    build: ./client
    environment:
      - SERVER_ADDR=server:8080
    depends_on:
      - server
    networks:
      - wow-net

networks:
  wow-net:
